// <auto-generated />
namespace Start.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PersonPersonNamesIndex : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PersonPersonNamesIndex));
        
        string IMigrationMetadata.Id
        {
            get { return "201811290757383_PersonPersonNamesIndex"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
